server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: trace

spring:
  application:
    name: GATEWAY-SERVER
  session:
    store-type: redis
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
        - SaveSession
      routes:
        - id: route
          uri: http://localhost:9191/
          predicates:
            - Path=/**
          filters:
            - name: Retry
              args:
                retries: 10
                methods: GET
                backoff:
                  firstBackoff: 1000ms
                  maxBackoff: 5000ms
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: client
            client-secret: secret
            scope: openid, profile
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: http://localhost:8080/login/oauth2/code/gateway
        provider:
          spring:
            issuer-uri: http://localhost:9000
