package com.jirafik.customer.model;

public enum OrderStatus {
    CUSTOMER_CREATED, CUSTOMER_PAID, CUSTOMER_CANCELLED,
    SHOP_ACCEPTED, SHOP_DENIED, SHOP_REFUNDED, SHOP_PREPARING,
    DELIVERY_PENDING, DELIVERY_DENIED, DELIVERY_REFUNDED, DELIVERY_DELIVERING, DELIVERY_COMPLETED
}
